// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALmsF0dXasZRI-sqNfRNs8-WrUpksUIjI',
    appId: '1:809243284544:web:3ed1b0f018d9139da0bba5',
    messagingSenderId: '809243284544',
    projectId: 'campus-intelligence',
    authDomain: 'campus-intelligence.firebaseapp.com',
    storageBucket: 'campus-intelligence.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC595mcOQh4sIW-iJR53vy0eURa8lgosJ0',
    appId: '1:809243284544:android:7f25a095fc0bff69a0bba5',
    messagingSenderId: '809243284544',
    projectId: 'campus-intelligence',
    storageBucket: 'campus-intelligence.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN7nF3clZgS7aqfAefsHnDcgrF_Wz3fL4',
    appId: '1:809243284544:ios:079b418f8458ab79a0bba5',
    messagingSenderId: '809243284544',
    projectId: 'campus-intelligence',
    storageBucket: 'campus-intelligence.firebasestorage.app',
    iosBundleId: 'com.example.campusIntelligence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN7nF3clZgS7aqfAefsHnDcgrF_Wz3fL4',
    appId: '1:809243284544:ios:079b418f8458ab79a0bba5',
    messagingSenderId: '809243284544',
    projectId: 'campus-intelligence',
    storageBucket: 'campus-intelligence.firebasestorage.app',
    iosBundleId: 'com.example.campusIntelligence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALmsF0dXasZRI-sqNfRNs8-WrUpksUIjI',
    appId: '1:809243284544:web:fa149243afe495d0a0bba5',
    messagingSenderId: '809243284544',
    projectId: 'campus-intelligence',
    authDomain: 'campus-intelligence.firebaseapp.com',
    storageBucket: 'campus-intelligence.firebasestorage.app',
  );
}
